=== themarioga/Commons-Engine/src/test/resources/schema.dtd
<!ELEMENT dataset (
        Lang*,
        Room*,
        Tag*,
        Users*)>

        <!ELEMENT Lang EMPTY>
        <!ATTLIST Lang
                ID CDATA #REQUIRED
                NAME CDATA #REQUIRED
                >

        <!ELEMENT Room EMPTY>
        <!ATTLIST Room
                ID CDATA #REQUIRED
                NAME CDATA #REQUIRED
                ACTIVE CDATA #REQUIRED
                CREATION_DATE CDATA #REQUIRED
                >

        <!ELEMENT Tag EMPTY>
        <!ATTLIST Tag
                TAG CDATA #REQUIRED
                TEXT CDATA #REQUIRED
                LANG_ID CDATA #REQUIRED
                >

        <!ELEMENT Users EMPTY>
        <!ATTLIST Users
                ID CDATA #REQUIRED
                NAME CDATA #REQUIRED
                ACTIVE CDATA #REQUIRED
                LANG_ID CDATA #REQUIRED
                CREATION_DATE CDATA #REQUIRED
                >

=== themarioga/Commons-Engine/src/test/resources/dbunit/service/setup/user.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dataset SYSTEM "src/test/resources/schema.dtd">
<dataset>
    <Users ID="00000000-0000-0000-0000-000000000000" NAME="First" ACTIVE="true" LANG_ID="es" CREATION_DATE="[now]"/>
    <Users ID="11111111-1111-1111-1111-111111111111" NAME="Second" ACTIVE="true" LANG_ID="es" CREATION_DATE="[now]"/>
    <Users ID="22222222-2222-2222-2222-222222222222" NAME="Third" ACTIVE="false" LANG_ID="es" CREATION_DATE="[now]"/>
    <Users ID="33333333-3333-3333-3333-333333333333" NAME="Fourth" ACTIVE="true" LANG_ID="es" CREATION_DATE="[now]"/>
    <Users ID="44444444-4444-4444-4444-444444444444" NAME="Fifth" ACTIVE="true" LANG_ID="es" CREATION_DATE="[now]"/>
    <Users ID="55555555-5555-5555-5555-555555555555" NAME="Sixth" ACTIVE="true" LANG_ID="es" CREATION_DATE="[now]"/>
    <Users ID="66666666-6666-6666-6666-666666666666" NAME="Seventh" ACTIVE="true" LANG_ID="es" CREATION_DATE="[now]"/>
</dataset>
